using System.Text;
using CLI.Models.Tekla;

namespace CLI.Services;

public sealed class TeklaObjectsWriter
{
    public void Write(TeklaObjectsFile file, string outputPath)
    {
        // Register encoding provider to support Windows-1252
        Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

        var sb = new StringBuilder();

        sb.AppendLine("/***************************************************************************/");
        sb.AppendLine($"/* {file.SheetName} - User Defined Attributes */");
        sb.AppendLine($"/* Generated by SnacksDto */");
        sb.AppendLine("/***************************************************************************/");
        sb.AppendLine();

        // Generate the primary object definition (first one in list) with full tab_page definition
        if (file.ObjectDefinitions.Count > 0)
        {
            var primaryDef = file.ObjectDefinitions[0];
            WriteObjectDefinitionWithTabPage(sb, primaryDef);
            sb.AppendLine();

            // Generate references for other object types
            for (int i = 1; i < file.ObjectDefinitions.Count; i++)
            {
                WriteObjectReference(sb, file.ObjectDefinitions[i]);
                sb.AppendLine();
            }
        }

        // Ensure directory exists
        var directory = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrEmpty(directory))
        {
            Directory.CreateDirectory(directory);
        }

        // Use ANSI encoding (Windows-1252) for Tekla compatibility with Norwegian characters æ, ø, å
        // UTF-8 BOM doesn't load in Tekla, UTF-8 without BOM has decoding errors
        var ansiEncoding = Encoding.GetEncoding(1252); // Windows-1252 (Western European)
        File.WriteAllText(outputPath, sb.ToString(), ansiEncoding);
    }

    private static void WriteObjectDefinitionWithTabPage(StringBuilder sb, TeklaObjectsDef objectDef)
    {
        sb.AppendLine("/***************************************************************************/");
        sb.AppendLine($"/* {objectDef.ObjectName} attributes */");
        sb.AppendLine("/***************************************************************************/");
        sb.AppendLine($"{objectDef.ObjectType}(0,\"{objectDef.ObjectName}\")");
        sb.AppendLine("{");

        // Write tab page
        var tabPage = objectDef.TabPage;
        sb.AppendLine($"\ttab_page(\"{tabPage.Name}\")");
        sb.AppendLine("\t{");

        // Write attributes
        foreach (var attr in tabPage.Attributes)
        {
            WriteAttribute(sb, attr, 2);
        }

        sb.AppendLine("\t}");

        // Write tab_page reference
        sb.AppendLine($"\ttab_page(\"{tabPage.Name}\", \"{tabPage.Label}\", 19)");
        sb.AppendLine("\tmodify (1)");
        sb.AppendLine("}");
    }

    private static void WriteObjectReference(StringBuilder sb, TeklaObjectsDef objectDef)
    {
        sb.AppendLine("/***************************************************************************/");
        sb.AppendLine($"/* {objectDef.ObjectName} attributes */");
        sb.AppendLine("/***************************************************************************/");
        sb.AppendLine($"{objectDef.ObjectType}(0,\"{objectDef.ObjectName}\")");
        sb.AppendLine("{");
        sb.AppendLine($"\t/* Reference to the user defined tab page defined in {objectDef.TabPage.Name} */");
        sb.AppendLine($"\ttab_page(\"{objectDef.TabPage.Name}\", \"{objectDef.TabPage.Label}\", 19)");
        sb.AppendLine("\tmodify (1)");
        sb.AppendLine("}");
    }

    private static void WriteAttribute(StringBuilder sb, TeklaAttribute attr, int indentLevel)
    {
        var indent = new string('\t', indentLevel);
        
        var attributeKeyword = attr.IsUnique ? "unique_attribute" : "attribute";

        // Build attribute line with optional positioning
        var attributeLine = $"{indent}{attributeKeyword}(\"{attr.Name}\", \"{attr.Label}\", {attr.ValueType}, \"{attr.FieldFormat}\", {attr.SpecialFlag}, {attr.CheckSwitch}, \"{attr.AttributeValueMin}\", \"{attr.AttributeValueMax}\"";
        
        // Add positioning parameters if present
        if (attr.X.HasValue && attr.Y.HasValue && attr.Width.HasValue)
        {
            attributeLine += $", {attr.X.Value}, {attr.Y.Value}, {attr.Width.Value}";
        }
        
        attributeLine += ")";
        
        sb.AppendLine(attributeLine);
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}\tvalue(\"\", 0)");
        sb.AppendLine($"{indent}}}");
    }
}
